# Generated by Django 5.0.3 on 2024-04-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Due",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.IntegerField()),
                ("dues", models.JSONField(default=list)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="due_invoice",
                        to="finance.invoice",
                    ),
                ),
            ],
        ),
    ]
