# Generated by Django 5.0.3 on 2024-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyattendance",
            name="date",
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
