# Generated by Django 5.0.3 on 2024-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_dailyattendance_date"),
        ("staffs", "0002_alter_staff_staff_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffDailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True, unique=True)),
                ("staffs", models.ManyToManyField(null=True, to="staffs.staff")),
            ],
        ),
    ]
